openai_input:
 name: OpenAI input
 description: Send a message to OpenAI chatgpt via APIs
 fields:
    prompt:
      name: Prompt
      description: The message to send
      required: true
      example: "Tell me what you can do"
      selector:
        text:
          multiline: true

    Instructions:
      name: Instructions
      description: How the bot should tune its response
      required: false
      example: "You are a helpful assistant with ironical responses"
      default: "You are a helpful assistant with ironical responses"
      selector:
        text:
          multiline: true

    model:
      name: Model
      advanced: true
      description: The model to use
      required: false
      example: "gpt-4-turbo-preview"
      default: "gpt-3.5-turbo"
      selector:
        text: 
          multiline: false

    max_tokens:
      name: Max Tokens
      description: The maximum number of tokens the AI model should generate in its completion of the prompt
      required: false
      example: 50
      default: 350
      selector:
        number:
          min: 1
          max: 4096
          step: 1
